{{- if .Values.ingress.enabled -}}
{{- $fullName := include "publicapi.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{ $prefix := default .Values.pr "" }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else -}}
apiVersion: networking.k8s.io/v1beta1
  {{- end }}
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "publicapi.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if eq "dev" .Values.env}}
    - host: {{ $prefix }}{{ .Values.hostname }}.dev.eisen.network
  {{- else }}
    - host: {{ .Values.hostname }}.{{ .Values.env }}.eisen.network
  {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  {{- end }}
