on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Promote Version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: version.yaml
